# https://kubernetes.io/docs/concepts/configuration/secret/
apiVersion: v1
kind: Secret
metadata:
  name: {{ $.Release.Name }}-forge
type: Opaque
data:
  POSTGRESQL: {{ $.Values.chutes_api.database_url | b64enc }}
  REDIS_URL: {{ $.Values.chutes_api.redis_url | b64enc }}

  MINIO_ENDPOINT: {{ $.Values.chutes_api.storage_endpoint | b64enc }}
  MINIO_ACCESS_KEY: {{ $.Values.chutes_api.storage_access_key | b64enc }}
  MINIO_SECRET_KEY: {{ $.Values.chutes_api.storage_secret_key | b64enc }}
  STORAGE_BUCKET: {{ $.Values.chutes_api.storage_bucket | b64enc }}

  REGISTRY_PASSWORD: {{ $.Values.chutes_api.registry_secret | b64enc }}
  REGISTRY_INSECURE: {{ $.Values.chutes_api.registry_insecure | toString | b64enc }}
---
