-- migrate:up
ALTER TABLE chutes ADD COLUMN IF NOT EXISTS readme TEXT default '';
ALTER TABLE chutes ADD COLUMN IF NOT EXISTS logo_id VARCHAR REFERENCES logos(logo_id) ON DELETE SET NULL;
ALTER TABLE images ADD COLUMN IF NOT EXISTS readme TEXT default '';
ALTER TABLE images ADD COLUMN IF NOT EXISTS logo_id VARCHAR REFERENCES logos(logo_id) ON DELETE SET NULL;

-- migrate:down
ALTER TABLE chutes DROP COLUMN IF EXISTS readme;
ALTER TABLE chutes DROP COLUMN IF EXISTS logo_id;
ALTER TABLE images DROP COLUMN IF EXISTS readme;
ALTER TABLE images DROP COLUMN IF EXISTS logo_id;
