-- migrate:up
ALTER TABLE chutes ADD COLUMN IF NOT EXISTS filename TEXT NOT NULL DEFAULT '';
ALTER TABLE chutes ADD COLUMN IF NOT EXISTS code TEXT NOT NULL DEFAULT '';
ALTER TABLE chutes ADD COLUMN IF NOT EXISTS version TEXT NOT NULL DEFAULT '';

-- migrate:down
ALTER TABLE chutes DROP COLUMN IF EXISTS filename;
ALTER TABLE chutes DROP COLUMN IF EXISTS code;
ALTER TABLE chutes DROP COLUMN IF EXISTS version;
