{{- if .Values.autostaker.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: autostaker
  labels:
    {{- include "autostaker.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.autostaker.replicaCount }}
  selector:
    matchLabels:
      {{- include "autostaker.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "autostaker.labels" . | nindent 8 }}
    spec:
      {{- with .Values.autostaker.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.autostaker.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- include "chutes.podSecurityContext" . | nindent 8 }}
      tolerations:
        {{- include "chutes.defaultTolerations" . | nindent 8 }}
        {{- with .Values.autostaker.tolerations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      containers:
        - name: autostaker
          image: {{ include "chutes.image" (list . .Values.autostaker.image) | quote }}
          imagePullPolicy: {{ .Values.autostaker.imagePullPolicy }}
          command:
            - uv
            - run
            - taskiq
            - worker
            - api.autostaker:broker
            - --workers
            - "1"
            - --max-async-tasks
            - "4"
          securityContext:
            {{- include "chutes.containerSecurityContext" . | nindent 12 }}
          env:
            {{- include "chutes.sensitiveEnv" . | nindent 12 }}
            {{- include "chutes.commonEnv" . | nindent 12 }}
            - name: SUBTENSOR_ADDRESS
              value: {{ .Values.autostaker.subtensor | quote }}
          resources:
            {{- toYaml .Values.autostaker.resources | nindent 12 }}
{{- end }}
