apiVersion: v1
kind: Service
metadata:
  name: cm-redis
  labels:
    {{- include "cmRedis.labels" . | nindent 4 }}
spec:
  type: {{ .Values.cmRedis.service.type }}
  ports:
    - port: {{ .Values.cmRedis.service.port }}
      targetPort: redis
      protocol: TCP
      name: redis
  selector:
    {{- include "cmRedis.labels" . | nindent 4 }}
