apiVersion: batch/v1
kind: CronJob
metadata:
  name: downscaler
  labels:
    {{- include "downscaler.labels" . | nindent 4 }}
spec:
  schedule: "*/45 * * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      backoffLimit: 2
      ttlSecondsAfterFinished: 15000
      template:
        metadata:
          labels:
            {{- include "downscaler.labels" . | nindent 12 }}
        spec:
          restartPolicy: Never
          {{- with .Values.downscaler.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.downscaler.affinity }}
          affinity:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.downscaler.tolerations }}
          tolerations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          containers:
            - name: downscaler
              image: "{{ .Values.downscaler.image }}"
              imagePullPolicy: {{ .Values.downscaler.imagePullPolicy }}
              command: ["poetry", "run", "python", "downscaler.py"]
              env:
                {{- include "chutes.sensitiveEnv" . | nindent 16 }}
                {{- include "chutes.commonEnv" . | nindent 16 }}
                - name: MEMCACHED
                  value: memcached
              resources:
                {{- toYaml .Values.downscaler.resources | nindent 16 }}
