apiVersion: v1
kind: Service
metadata:
  name: llm-cache-redis
  labels:
    {{- include "llmCacheRedis.labels" . | nindent 4 }}
spec:
  type: {{ .Values.llmCacheRedis.service.type }}
  ports:
    - port: {{ .Values.llmCacheRedis.service.port }}
      targetPort: redis
      protocol: TCP
      name: redis
  selector:
    {{- include "llmCacheRedis.labels" . | nindent 4 }}
