{{- if .Values.metasync.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: metasync
  labels:
    {{- include "metasync.labels" . | nindent 4 }}
spec:
  schedule: "*/3 * * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      backoffLimit: 2
      ttlSecondsAfterFinished: 7200
      activeDeadlineSeconds: 120
      template:
        metadata:
          labels:
            {{- include "metasync.labels" . | nindent 12 }}
        spec:
          restartPolicy: Never
          {{- with .Values.metasync.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.metasync.affinity }}
          affinity:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.metasync.tolerations }}
          tolerations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          containers:
            - name: metasync
              image: "{{ .Values.metasync.image }}"
              imagePullPolicy: {{ .Values.metasync.imagePullPolicy }}
              command: ["python", "metasync/sync_metagraph.py"]
              env:
                - name: SUBTENSOR_ADDRESS
                  value: {{ .Values.metasync.subtensor }}
                - name: POSTGRESQL
                  valueFrom:
                    secretKeyRef:
                      name: postgres-secret
                      key: url
                - name: REDIS_URL
                  valueFrom:
                    secretKeyRef:
                      name: redis-secret
                      key: url
              resources:
                {{- toYaml .Values.metasync.resources | nindent 16 }}
{{- end }}
