{{- if .Values.paymentWatcher.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: payment-watcher
  labels:
    {{- include "paymentWatcher.labels" . | nindent 4 }}
spec:
  type: {{ .Values.paymentWatcher.service.type | default "ClusterIP" }}
  ports:
    - port: {{ .Values.paymentWatcher.service.port }}
      targetPort: {{ .Values.paymentWatcher.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "paymentWatcher.labels" . | nindent 4 }}
{{- end }}
