apiVersion: apps/v1
kind: Deployment
metadata:
  name: quota-redis
  labels:
    {{- include "quotaRedis.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.quotaRedis.replicaCount }}
  selector:
    matchLabels:
      {{- include "quotaRedis.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "quotaRedis.labels" . | nindent 8 }}
    spec:
      {{- with .Values.quotaRedis.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.quotaRedis.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.quotaRedis.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: redis
          image: "{{ .Values.quotaRedis.image }}"
          imagePullPolicy: {{ .Values.quotaRedis.imagePullPolicy }}
          args:
            - redis-server
            - --requirepass
            - $(REDIS_PASSWORD)
            {{- range .Values.quotaRedis.config.customArgs }}
            - {{ . }}
            {{- end }}
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-secret
                  key: password
          ports:
            - name: redis
              containerPort: {{ .Values.quotaRedis.service.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.quotaRedis.resources | nindent 12 }}
