apiVersion: v1
kind: Service
metadata:
  name: req-hash-dns
  labels:
    {{- include "reqHashDns.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - port: {{ .Values.reqHashDns.service.port }}
      nodePort: {{ .Values.reqHashDns.service.nodePort }}
      targetPort: {{ .Values.reqHashDns.service.port }}
      protocol: UDP
      name: req-dns-udp
  selector:
    {{- include "reqHashDns.labels" . | nindent 4 }}
