{{- if .Values.reqHashDns.enabled }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: req-hash-dns
  labels:
    {{- include "reqHashDns.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "reqHashDns.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "reqHashDns.labels" . | nindent 8 }}
    spec:
      {{- with .Values.reqHashDns.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.reqHashDns.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.reqHashDns.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: dns
          image: "{{ .Values.reqHashDns.image }}"
          imagePullPolicy: {{ .Values.reqHashDns.imagePullPolicy }}
          command: ["poetry", "run", "python", "request_hash_dns.py"]
          env:
            {{- include "chutes.commonEnv" . | nindent 12 }}
            - name: MEMCACHED
              value: memcached
          resources:
            {{- toYaml .Values.reqHashDns.resources | nindent 12 }}
          ports:
            - containerPort: {{ .Values.reqHashDns.service.port }}
              protocol: UDP
              name: req-dns-udp
{{- end }}
