class UnsafeExtraction(RuntimeError): ...


class BuildFailure(RuntimeError): ...


class BuildTimeout(TimeoutError): ...


class PushFailure(RuntimeError): ...


class PushTimeout(TimeoutError): ...
