"""
GPU constants, expected values, etc.
"""

# GPUs that are allowed to be passed in node_selector as "include" arg,
# because they are likely to be specified and somewhat widely available.
ALLOWED_INCLUDE = {
    "4090",
    "a6000",
    "l40s",
    "a100",
    "h100",
    "h100_sxm",
    "h200",
}
SUPPORTED_GPUS = {
    "3090": {
        "model_name_check": "RTX 3090",
        "memory": 24,
        "major": 8,
        "minor": 6,
        "tensor_cores": 328,
        "processors": 82,
        "clock_rate": {"base": 1395, "boost": 1695},
        "max_threads_per_processor": 1536,
        "concurrent_kernels": True,
        "ecc": False,
        "sxm": False,
        "hourly_rate": 0.3225,
    },
    "4090": {
        "model_name_check": "RTX 4090",
        "memory": 24,
        "major": 8,
        "minor": 9,
        "tensor_cores": 512,
        "processors": 128,
        "clock_rate": {"base": 2235, "boost": 2520},
        "max_threads_per_processor": 1536,
        "concurrent_kernels": True,
        "ecc": False,
        "sxm": False,
        "hourly_rate": 0.5175,
    },
    "a4000": {
        "model_name_check": "RTX A4000",
        "memory": 16,
        "major": 8,
        "minor": 6,
        "tensor_cores": 168,
        "processors": 48,
        "clock_rate": {"base": 765, "boost": 1560},
        "max_threads_per_processor": 1536,
        "concurrent_kernels": True,
        "ecc": True,
        "sxm": False,
        "hourly_rate": 0.24,
    },
    "a5000": {
        "model_name_check": "RTX A5000",
        "memory": 24,
        "major": 8,
        "minor": 6,
        "tensor_cores": 256,
        "processors": 64,
        "clock_rate": {"base": 1170, "boost": 1695},
        "max_threads_per_processor": 1536,
        "concurrent_kernels": True,
        "ecc": False,
        "sxm": False,
        "hourly_rate": 0.27,
    },
    "a6000": {
        "model_name_check": "RTX A6000(?! Ada)",
        "memory": 48,
        "major": 8,
        "minor": 6,
        "tensor_cores": 336,
        "processors": 84,
        "clock_rate": {"base": 1455, "boost": 1860},
        "max_threads_per_processor": 1536,
        "concurrent_kernels": True,
        "ecc": True,
        "sxm": False,
        "hourly_rate": 0.57,
    },
    "a6000_ada": {
        "model_name_check": "RTX A6000 Ada",
        "memory": 48,
        "major": 8,
        "minor": 9,
        "tensor_cores": 568,
        "processors": 142,
        "clock_rate": {"base": 915, "boost": 2505},
        "max_threads_per_processor": 1536,
        "concurrent_kernels": True,
        "ecc": True,
        "sxm": False,
        "hourly_rate": 0.66,
    },
    "l4": {
        "model_name_check": "L4(?!0)",
        "memory": 24,
        "major": 8,
        "minor": 9,
        "tensor_cores": 240,
        "processors": 58,
        "clock_rate": {"base": 795, "boost": 2040},
        "max_threads_per_processor": 1536,
        "concurrent_kernels": True,
        "ecc": True,
        "sxm": False,
        "hourly_rate": 0.3225,
    },
    "a10": {
        "model_name_check": "A10(?!0)",
        "memory": 24,
        "major": 8,
        "minor": 6,
        "tensor_cores": 208,
        "processors": 72,
        "clock_rate": {"base": 1110, "boost": 1710},
        "max_threads_per_processor": 1536,
        "concurrent_kernels": True,
        "ecc": True,
        "sxm": False,
        "hourly_rate": 0.5625,
    },
    "a40": {
        "model_name_check": "A40",
        "memory": 48,
        "major": 8,
        "minor": 6,
        "tensor_cores": 336,
        "processors": 84,
        "clock_rate": {"base": 1305, "boost": 1740},
        "max_threads_per_processor": 1536,
        "concurrent_kernels": True,
        "ecc": True,
        "sxm": False,
        "hourly_rate": 0.2925,
    },
    "l40": {
        "model_name_check": "L40(?!S)",
        "memory": 48,
        "major": 8,
        "minor": 9,
        "tensor_cores": 568,
        "processors": 142,
        "clock_rate": {"base": 735, "boost": 2490},
        "max_threads_per_processor": 1536,
        "concurrent_kernels": True,
        "ecc": True,
        "sxm": False,
        "hourly_rate": 0.6,
    },
    "l40s": {
        "model_name_check": "L40S",
        "memory": 48,
        "major": 8,
        "minor": 9,
        "tensor_cores": 568,
        "processors": 142,
        "clock_rate": {"base": 1065, "boost": 2520},
        "max_threads_per_processor": 1536,
        "concurrent_kernels": True,
        "ecc": True,
        "sxm": False,
        "hourly_rate": 0.71,
    },
    "a100_40gb": {
        "model_name_check": "A100.?PCIE.?40GB",
        "memory": 40,
        "major": 8,
        "minor": 0,
        "tensor_cores": 432,
        "processors": 108,
        "clock_rate": {"base": 1065, "boost": 1410},
        "max_threads_per_processor": 2048,
        "concurrent_kernels": True,
        "ecc": True,
        "sxm": False,
        "hourly_rate": 0.9375,
    },
    "a100_40gb_sxm": {
        "model_name_check": "A100.?SXM.?40GB",
        "memory": 40,
        "major": 8,
        "minor": 0,
        "tensor_cores": 432,
        "processors": 108,
        "clock_rate": {"base": 1065, "boost": 1410},
        "max_threads_per_processor": 2048,
        "concurrent_kernels": True,
        "ecc": True,
        "sxm": True,
        "hourly_rate": 0.9375,
    },
    "a100": {
        "model_name_check": "A100.?80GB.?PCIe",
        "memory": 80,
        "major": 8,
        "minor": 0,
        "tensor_cores": 432,
        "processors": 108,
        "clock_rate": {"base": 1065, "boost": 1410},
        "max_threads_per_processor": 2048,
        "concurrent_kernels": True,
        "ecc": True,
        "sxm": False,
        "hourly_rate": 1.0125,
    },
    "a100_sxm": {
        "model_name_check": "A100.?SXM.?.?80GB",
        "memory": 80,
        "major": 8,
        "minor": 0,
        "tensor_cores": 432,
        "processors": 108,
        "clock_rate": {"base": 1275, "boost": 1410},
        "max_threads_per_processor": 2048,
        "concurrent_kernels": True,
        "ecc": True,
        "sxm": True,
        "hourly_rate": 1.0125,
    },
    "h100": {
        "model_name_check": "H100.*PCIe",
        "memory": 80,
        "major": 9,
        "minor": 0,
        "tensor_cores": 456,
        "processors": 114,
        "clock_rate": {"base": 1095, "boost": 1755},
        "max_threads_per_processor": 2048,
        "concurrent_kernels": True,
        "ecc": True,
        "sxm": False,
        "hourly_rate": 1.425,
    },
    "h100_sxm": {
        "model_name_check": "H100.*HBM3",
        "memory": 80,
        "major": 9,
        "minor": 0,
        "tensor_cores": 528,
        "processors": 132,
        "clock_rate": {"base": 1590, "boost": 1980},
        "max_threads_per_processor": 2048,
        "concurrent_kernels": True,
        "ecc": True,
        "sxm": True,
        "hourly_rate": 1.8300,
    },
    "h200": {
        "model_name_check": " H200",
        "memory": 140,
        "major": 9,
        "minor": 0,
        "tensor_cores": 528,
        "processors": 132,
        "clock_rate": {"base": 1590, "boost": 1980},
        "max_threads_per_processor": 2048,
        "concurrent_kernels": True,
        "ecc": True,
        "sxm": True,
        "hourly_rate": 2.7375,
    },
}


def normalize_scores(gpu_dict):
    """
    Calculate score for each supported GPU and provide a normalized range (based on price).
    """
    scores = {}
    for model, info in gpu_dict.items():
        score = info["hourly_rate"]
        scores[model] = score
    sorted_scores = dict(sorted(scores.items(), key=lambda x: x[1], reverse=True))
    max_score = max(scores.values())
    normalized_scores = {}
    for model, score in sorted_scores.items():
        normalized_scores[model] = score / max_score
    return normalized_scores


COMPUTE_MULTIPLIER = normalize_scores(SUPPORTED_GPUS)
COMPUTE_MIN = min([score for score in COMPUTE_MULTIPLIER.values()])
COMPUTE_UNIT_PRICE_BASIS = max([info["hourly_rate"] for info in SUPPORTED_GPUS.values()])
